### PR TITLE
feat: colors module provide function instead of value

### PR DESCRIPTION
**Pull request by nanozuki**

### CODE REVIEW

**Comment by ehrand** [comment]
With this change my colorscheme is not respected anymore. Searching for some hints in docs did not provide any help yet. Reverting back to commit c48af54a397bdae0f86e7000d35455bafcfa4a45 fixes the problem for me. Is there some way available to make this plugin (which I really love) follow my colorscheme?

**Comment by nanozuki** [comment]
@ehrand Oh, I'm sorry for that. I change the default colors because some color schemes do not set a good highlight group for `TabLine`, `TabLineSel`, and `TabLineFill`. So I use color from terminal colors instead.

Yes, it can be changed by config, but first, can you tell me the repo of the color scheme you use and the screenshot of the two versions? It will help me think more about this question and provider a option to solve this breaking change.

**Comment by nanozuki** [comment]
After some thinking, Because the new version of tabby is developing, It's better to not provide a breaking update in the current version, I revert it. Welcome the following feedback.

**Comment by ehrand** [comment]
@nanozuki thank you, now it looks beautiful again :). Colorschem I'm using is this: https://github.com/sainnhe/gruvbox-material

**Pull request merged**
