### PR TITLE
Buffers

### PR DESCRIPTION
**Pull request by nanozuki**

### CODE REVIEW

**Comment by nanozuki** [comment]
@capsey Sorry for being late. I'm back! I finally merged this. I moved "filters" to another method of "bufs." I am eager for your feedback!

**Comment by igorlfs** [comment]
Hello! This PR broke my config :(

Previously, I was using

```lua
name_fallback = function(tabid)
    local winid = api.get_tab_current_win(tabid)
    local bufnr = api.get_win_buf(winid)
    local buftype = vim.fn.getbufvar(bufnr, "&buftype")
    local filetype = vim.fn.getbufvar(bufnr, "&filetype")

    if api.is_float_win(winid) then
       -- some stuff
    else
        local name = buf_name.get(winid)
        if vim.bo[vim.api.nvim_win_get_buf(winid)].modified then
            return name .. " ●"
        else
            return name
        end
    end
end
```

I thought I'd simply have the line from

```lua
        local name = buf_name.get(winid)
```

to

```lua
        local name = buf_name.get(bufnr)
```

But all I get is a bunch of "[No Name]" tabs, eg

image

**Comment by nanozuki** [comment]
@igorlfs Fixed in latest commit [t0d5af](https://github.com/nanozuki/tabby.nvim/commit/0d5af4f2b747dbba38f2ee9fa99caa080f41d419)

**Comment by igorlfs** [comment]
> @igorlfs Fixed in latest commit [t0d5af](https://github.com/nanozuki/tabby.nvim/commit/0d5af4f2b747dbba38f2ee9fa99caa080f41d419)

Thanks!

**Comment by capsey** [comment]
> @capsey Sorry for being late. I'm back! I finally merged this. I moved "filters" to another method of "bufs." I am eager for your feedback!

Wow, this is great! It works beautifully, other than small hiccups (#163)

Last thing, since I am using `scope.nvim`, I used an autocommand to flush the unique name cache on `TabEnter` using `require("tabby.module.filename").flush_unique_name_cache()`, however since you rewrote that module's functionality using `FileNameResolver` in `lua/tabby/feature/buf_name.lua` and `lua/tabby/feature/win_name.lua`, could you expose a function for running local `resolver:flush()`? Should I create an issue for that?

**Comment by nanozuki** [comment]
> Could you expose a function for running local `resolver:flush()`? Should I create an issue for that?

Oh, this is necessary. I will do this in these two days. I created an issue to notify me.

**Pull request merged**
